# Dockerfile.stg
# ================================
# 1) 빌드 스테이지 (Gradle + JDK 21)
# ----------------
# Gradle JDK 21 환경에서 애플리케이션 JAR 빌드
FROM gradle:jdk-21-and-23-graal-jammy AS builder
WORKDIR /app

# Gradle 캐시 최적화를 위해 설정 파일 먼저 복사
COPY build.gradle settings.gradle ./
RUN gradle wrapper
RUN ./gradlew dependencies --no-daemon

# 소스 및(있다면) .env 복사 (.env가 없어도 빌드는 진행됨)
COPY src src
COPY .env .env

# 테스트 제외 빌드 → app.jar 생성
RUN ./gradlew build --no-daemon -x test
# plain JAR 정리
RUN rm -rf /app/build/libs/*-plain.jar


# ================================
# 2) 실행 스테이지 (GraalVM JDK 23)
# ----------------
FROM container-registry.oracle.com/graalvm/jdk:23
WORKDIR /app

# 빌드 결과 JAR 복사
COPY --from=builder /app/build/libs/app.jar app.jar

# 서비스 포트(가시성용)
EXPOSE 8080
# 실행할 JAR 파일 지정
ENTRYPOINT ["java", "-Dspring.profiles.active=stg,secret", "-jar", "app.jar"]
