# application-stg.yml

spring:
  datasource:
    url: jdbc:mysql://mysql_1:3306/glog_prod?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: lldjlocal
    password: ${custom.stg.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis_1
      port: 6379
      password: ${custom.stg.redis.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 100

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

custom:
  site:
    domain: api.app.choiyb.shop      # stg.choiyb.shop → api.app.choiyb.shop
    backUrl: https://api.stg.choiyb.shop
    frontUrl: https://stg.choiyb.shop

cors:
  allowed-origins:
    - "https://stg.choiyb.shop"
    - "http://localhost:3000"
    - "http://api.app.choiyb.shop"
    - "http://localhost:5173"
  allowed-origin-patterns:
    - "https://*.vercel.app"
