# 실제 배포중인 운영 서버에 대한 설정
#application-prod.yml
spring:
  data:
    redis:
      host: localhost
      password: ${custom.prod.redis.password}
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/myweb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url: jdbc:mysql://mysql-1:3306/myweb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${custom.prod.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
logging:
  level: # 배포환경에서는 INFO 레벨만 기록하여 성능, 보안, 로그 용량 관리를 최적화
    com.example: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO

custom:
  site:
    domain: choiyb.shop
    backUrl: https://choiyb.shop
    frontUrl: