# application-secret.yml (수정본)
spring:
  datasource:
    password: Abcd123@

  mail:
    username: 'uswbookverify@gmail.com'
    password: ''

custom:
  jwt:
    secret-key: ''
    access-token-expire-seconds: 900
    refresh-token-expire-seconds: 604800

  prod:
    db:
      password: '1234'
    redis:
      password: '0000'

  stg:
    db:
      password: '1234'
    redis:
      password: '0000'

